spring.profiles.active=dev
# Application
spring.application.name=future_backend
server.port=19093

# Database credentials
db.username=root
db.password=XiongDWM01231996.

# Platform Database
platform.datasource.url=jdbc:mysql://pal_db:3306/future_platform?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true

# Tenant Database
tenant.datasource.url-template=jdbc:mysql://pal_db:3306/{db}?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
tenant.datasource.default-db=future_db

# Jackson
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=Asia/Shanghai

# virtual thread
spring.threads.virtual.enabled=true

# netty
spring.netty.event-loop-thread-count=4

# hikari
spring.datasource.hikari.maximum-pool-size=5



# Logging
logging.level.root=ERROR
logging.level.com.xiongdwm.future_backend=INFO

# JWT
jwt.expiration-ms=300000

# Customized Properties
file.upload.dir=/var/images/