# Application
server.port=19093

# Database credentials
db.username=root
db.password=XiongDWM01231996.

# Platform Database
platform.datasource.url=jdbc:mysql://129.204.87.172:13301/future_platform?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true

# Tenant Database
tenant.datasource.url-template=jdbc:mysql://129.204.87.172:13301/{db}?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
tenant.datasource.default-db=future_db

# Jackson
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=Asia/Shanghai

# Logging
logging.level.root=ERROR
logging.level.com.xiongdwm.future_backend=INFO

# JWT
jwt.expiration-ms=1800000

# Customized Properties
file.upload.dir=/Users/xiong/Program/future/files/images/

project.dev=false
