# Application
spring.profiles.active=dev
spring.application.name=future_backend
server.port=19093

# Database credentials
db.username=root
db.password=XiongDWM01231996.

# Tenant Database
tenant.datasource.default-db=future_db

# Jackson
spring.jackson.date-format=yyyy-MM-dd HH:mm:ss
spring.jackson.time-zone=Asia/Shanghai

# Virtual Thread
spring.threads.virtual.enabled=true

# Netty
spring.netty.event-loop-thread-count=4

# HikariCP
spring.datasource.hikari.maximum-pool-size=5

# Logging
logging.level.root=ERROR
logging.level.com.xiongdwm.future_backend=INFO
